export const ADD_ALL_COUNTRIES = "ADD_ALL_COUNTRIES";
export const ADD_ID_COUNTRY = "ADD_ID_COUNTRY";
export const SEARCH_COUNTRY = "SEARCH_COUNTRY";
export const RESET = "RESET";
export const ADD_ACTIVITY = "ADD_ACTIVITY"